"""initial_schema

Revision ID: ae0b98f2ca39
Revises: 
Create Date: 2026-03-21 23:04:38.167855

"""
from alembic import op
import sqlalchemy as sa


revision = 'ae0b98f2ca39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
